#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server:
# Requirements:
# - Accepts 4 parameters
#   - The path to the file to be transferred
#   - The IP of the server we want to transfer the file to
#   - The username scp connects with
#   - The path to the SSH private key that scp uses
# - Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 4 parameters passed
# - scp must transfer the file to the user home directory ~/
# - Strict host key checking must be disabled when using scp

declare file=$1
declare ip=$2
declare username=$3
declare ssh_key=$4

if [[ $# -eq 4 ]]; then
    scp -i "$ssh_key" -o StrictHostKeyChecking=no "$file" "$username"@"$ip":
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
