#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt -y update
sudo apt install -y --allow-downgrades nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i "/listen 80 default_server/a\ \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo sed -i "/TGUlwu4 permanent;/a\ \\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
