#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
#  - The name of the custom HTTP header must be X-Served-By
#  - The value of the custom HTTP header must be the hostname of the server Nginx is running on
# Write 0-custom_http_response_header so that it configures a brand new Ubuntu machine
# to the requirements asked in this task

if [ ! -x /usr/sbin/nginx ]; then
    sudo apt -y update
    sudo apt install -y --allow-downgrades nginx
    sudo ufw allow 'Nginx HTTP'
fi
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i "/listen 80 default_server/a\ \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n \
\terror_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo sed -i "54i\ \t\tadd_header X-Served-By ${HOSTNAME};\n" /etc/nginx/sites-available/default
sudo service nginx restart
