#!/usr/bin/env bash
# Pings an IP address passed as an argument:
# - Accepts a string as an argument
# - Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# - Ping the IP 5 times

args="${#@}"
ip_address="$1"

if [ "$args" -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$ip_address"
fi
