#!/usr/bin/env bash
# Displays 'bad luck' at 4th iteration and 'good' luck at 8th.
# Otherwise 'Best School in a while loop of 10 times

counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
