#!/usr/bin/env bash
# Gives information about specific file

file="school"
if [ -e "$file" ]; then
    echo "$file file exists"

    if [ -f "$file" ]; then
        echo "school is a regular file"
    fi

    if [ ! -s "$file" ]; then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
else
    echo "$file file does not exist"
fi
