#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except the TCP ports:
# 22 (SSH), 443 (HTTPS SSL), 80 (HTTP)

sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
