#!/usr/bin/env bash
# Script that runs Nginx as the nginx user
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
pkill -f apache2
sudo -u nginx service nginx restart
