#!/usr/bin/env bash
# Write a Bash script that uses ssh to connect to your server using
# the private key ~/.ssh/school with the user ubuntu.
# Requirements:
# - Only use ssh single-character flags
# - You cannot use -l
# - You do not need to handle the case of a private key protected by a passphrase

# -i [identity_file] [username@remote_host]
ssh -i ~/.ssh/school ubuntu@52.201.246.143
